version: '3.9'
services:
  admin_backend:
    build: . 
    image: invista/admin:0.0.24
    command: "python manage.py runserver 0.0.0.0:8000"
    container_name: admin-ms
    volumes:
      - .:/app
    ports:
      - 8002:8000
    env_file:
      - .env
    # networks:
    #   - admin
      # - users

  # admin_queue:
  #   build: .
  #   command: "python consumer.py"
  #   # depends_on:
  #   #   - admin_db
  #   networks:
  #     - admin

  # admin_redis:
  #   image: redis
  #   ports: 
  #     - 6379:6379
  #   networks:
  #     - admin

# networks:
#   admin:
#   users:
#     external:
#       name: users