version: '3.9'
services:
  admin_backend:
    build: . 
    image: invista/admin:0.0.24
    command: "python manage.py runserver 0.0.0.0:8000"
    container_name: admin-ms
    volumes:
      - .:/app
    ports:
      - 8002:8000
    env_file:
      - .env
