# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations

def update_valor_total_servico(apps, schema_editor):
    Servico = apps.get_model('core', 'Servico')
    Chapa = apps.get_model('core', 'Chapa')
    for servico in Servico.objects.all():
        chapa = Chapa.objects.get(pk=servico.chapa.id)
        valor_total = servico.quantidade * chapa.valor
        print(servico.id,valor_total)
        servico.valor_total_servico = valor_total
        servico.save(update_fields=['valor_total_servico'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_categoriaentrada_categoriasaida_entradachapa_and_more'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        # migrations.RunPython(update_valor_total_servico, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_valor_total_servico),
    ]