# Generated by Django 4.1.2 on 2022-12-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_update_valor_total_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupoclientenota",
            name="nota",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.nota"
            ),
        ),
    ]
