# Generated by Django 4.1.2 on 2022-12-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_grupoclientenota_nota"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="cliente_nome",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
