# Generated by Django 4.1.2 on 2022-11-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_categoriaentrada_categoriasaida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saidachapa",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.categoriasaida"
            ),
        ),
    ]
