# Generated by Django 4.1.2 on 2022-11-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_entradachapa_observacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saidachapa",
            name="observacao",
            field=models.TextField(null=True),
        ),
    ]
