# Generated by Django 4.1.2 on 2022-11-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_saidachapa_observacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradachapa",
            name="marca",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="entradachapa",
            name="valor_unitario",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
