# Generated by Django 4.1.2 on 2022-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_entradachapa_marca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradachapa",
            name="marca",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="entradachapa",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entradachapa",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="saidachapa",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
