# Generated by Django 4.1.2 on 2022-12-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_saidas"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaEntrada",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaSaida",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EntradaChapa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "valor_unitario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("data", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.categoriaentrada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaidaChapa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("data", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.categoriasaida",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Saidas",
        ),
        migrations.AddField(
            model_name="nota",
            name="valor_total_nota",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="Total"
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="valor_total_servico",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="chapa",
            name="estoque",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Quantidade em Estoque",
            ),
        ),
        migrations.AlterField(
            model_name="chapa",
            name="marca",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="Marca"
            ),
        ),
        migrations.AlterField(
            model_name="chapa",
            name="obs",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, verbose_name="Obs"
            ),
        ),
        migrations.AlterField(
            model_name="chapa",
            name="valor",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Valor"),
        ),
        migrations.AddField(
            model_name="saidachapa",
            name="chapa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.chapa"
            ),
        ),
        migrations.AddField(
            model_name="entradachapa",
            name="chapa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.chapa"
            ),
        ),
    ]
