# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations

def update_valor_total_nota(apps, schema_editor):
    Servico = apps.get_model('core', 'Servico')
    Nota = apps.get_model('core', 'Nota')
    GrupoNotaServico = apps.get_model('core', 'GrupoNotaServico')
    for nota in Nota.objects.all():
        gropo_nota_servicos = GrupoNotaServico.objects.filter(nota_id=nota.id)
        valor_total = 0
        for nota_servico in gropo_nota_servicos:
            servico = Servico.objects.get(pk=nota_servico.servico.id)
            valor_total = valor_total + servico.valor_total_servico
        nota.valor_total_nota = valor_total
        nota.save(update_fields=['valor_total_nota'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_update_valor_total_servico'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        # migrations.RunPython(update_valor_total_servico, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_valor_total_nota),
    ]