# Generated by Django 4.1.2 on 2022-11-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_kafkaerror"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="valor_total_nota",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="valor_total_servico",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="Total"
            ),
        ),
    ]
