"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# manage.py already loads the .env, but wsgi does not go through it: under
# gunicorn the settings are imported directly. Loading here covers both paths.
load_dotenv()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _list_from_env(name, default):
    """Read a comma-separated env var, trimming whitespace and dropping empties.

    Args:
        name: Environment variable name.
        default: Comma-separated fallback used when the variable is unset.

    Returns:
        A list of non-empty strings.
    """
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


def _bool_from_env(name, default="False"):
    """Read a boolean env var, accepting the usual truthy spellings.

    Args:
        name: Environment variable name.
        default: Fallback used when the variable is unset.

    Returns:
        True when the value is one of "1", "true", "yes" or "on"
        (case-insensitive); False otherwise.
    """
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Signs Django sessions and the JWTs issued in core/authentication.py.
# Intentionally has no default: better for the app to refuse to start than to
# start signing tokens with a known secret.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY is not set. Configure it in the local .env or in the "
        "deployment environment variables."
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False on purpose: the unsafe value has to be opted into
# explicitly, so forgetting to set the variable fails closed. With debug on,
# any error returns a stack trace exposing source code and configuration.
DEBUG = _bool_from_env("DEBUG", "False")

# Accepted Host headers. This used to be ['*'], which accepts any Host and
# opens the door to header poisoning. ".herokuapp.com" covers the app domain
# and platform subdomains; localhost covers development.
ALLOWED_HOSTS = _list_from_env(
    "ALLOWED_HOSTS",
    ".herokuapp.com,localhost,127.0.0.1",
)

AUTH_USER_MODEL = "core.User"

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "core"
)

MIDDLEWARE = (
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middlewares.AuthMiddleware',
)

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://admin_redis:6379/0",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",  # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        "NAME": os.getenv('DB_DATABASE'),  # Or path to database file if using sqlite3.
        "USER": os.getenv('DB_USERNAME'),
        "PASSWORD": os.getenv('DB_PASSWORD'),
        "HOST": os.getenv('DB_HOST'),  # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        "PORT": os.getenv('DB_PORT'),  # Set to empty string for default.
    }
}



# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Origins allowed to call the API. This used to be CORS_ORIGIN_ALLOW_ALL which,
# combined with CORS_ALLOW_CREDENTIALS, let ANY website issue authenticated
# requests using the victim's cookie. Env-driven so a new origin can be added
# without a deploy.
CORS_ALLOWED_ORIGINS = _list_from_env(
    "CORS_ALLOWED_ORIGINS",
    "https://admin.invistapublicidade.com,http://localhost:4200",
)

# Required because authentication travels in a cookie: without this the browser
# will not send credentials on cross-origin requests.
CORS_ALLOW_CREDENTIALS = True

# DRF now defaults to CLOSED: every view requires JWT authentication unless it
# explicitly opts out. This way a new view is born protected instead of relying
# on someone remembering to protect it. Exceptions are marked with AllowAny and
# justified case by case.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
