version: '3.9'

services:
  financeiro_backend:
    build: . 
    command: "python manage.py runserver 0.0.0.0:8000"
    container_name: financeiro-ms
    volumes:
      - .:/app
    ports:
      - 8003:8000
    environment:
      BOOTSTRAP_SERVERS: pkc-ldjyd.southamerica-east1.gcp.confluent.cloud:9092
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME: MABSYUGWW23PZAFB
      SASL_PASSWORD: ZgFhk8CANir6A17SoxYlv2Pz4ReQAROtrr1yIYVBHIcFGWG+xyP5+xDWxFFqz2lA
      SASL_MECHANISM: PLAIN
      GROUP_ID: myGroup
      KAFKA_TOPIC: financeiro_topic
      DB_HOST: invista-financeiro-db.cr6ld9unj4h4.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_DATABASE: invista_financeiro
      DB_USERNAME: postgres
      DB_PASSWORD: nfjy1994
      USERS_MS: http://users-ms:8000
      REDIS_URL: redis://financeiro_redis:6379/0
    # depends_on:
      # - financeiro_db
      # - financeiro_redis
    networks:
      - financeiro
      - users

  financeiro_queue:
    build: .
    command: "python consumer.py"
    # depends_on:
    #   - financeiro_db
    networks:
      - financeiro

  # financeiro_db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: financeiro
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: a
  #   volumes:
  #     - .dbdata:/var/lib/postgres
  #   ports:
  #     - 5437:5432
  #   networks:
  #     - financeiro

  # financeiro_redis:
  #   image: redis
  #   ports: 
  #     - 6380:6379
  #   networks:
  #     - financeiro

networks:
  financeiro:
  users:
    external:
      name: users