apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /api/admin/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-backend
                port:
                  number: 8002
          - path: /api/financeiro/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: financeiro-backend
                port:
                  number: 8003