version: '3.9'

services:
  users_backend:
    build: . 
    container_name: users-ms
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - users_db
    networks:
      - users

  users_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 5435:5432
    networks:
      - users

networks:
  users:
    name: users