version: '3.9'
services:
  users_backend:
    build: . 
    container_name: users-ms
    volumes:
      - .:/app
    environment:
      DB_HOST: 34.95.212.65
      DB_PORT: 5432
      DB_DATABASE: users
      DB_USERNAME: postgres
      DB_PASSWORD: nfjy1994
    ports:
      - 8001:8000
    # depends_on:
    #   - users_db
    networks:
      - users

  # users_db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     DB_HOST: 34.95.212.65
  #     DB_PORT: 5432
  #     DB_DATABASE: users
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: nfjy1994
  #   # volumes:
  #   #   - .dbdata:/var/lib/postgres
  #   ports:
  #     - 5435:5432
  #   networks:
  #     - users

networks:
  users:
    name: users